import 'package:om_chauhan/all_imports.dart';

class ProjectController {
  final projectList = [
    ProjectModel(
      title: 'Pixi Walls - HD Wallpapers',
      appLogo: 'https://play-lh.googleusercontent.com/0AABKLfoNQACiNKryZQwuX9f-7zDJatbg0jMuhn4njnT8FhOMhvY_n4t0V1l2Se0IW0=w240-h480-rw',
      description:
          "Best Android App for Stunning Backgrounds: HD Wallpapers 🇮🇳 \nFor your Android device, are you looking for a stunning collection of Full HD wallpapers? Full HD Wallpaper is the best app for beautiful backgrounds, so look no further!",
      website: '',
      gitHub: '',
      demo: '',
      screenshot: Screenshots.pixiWalls,
      miStore: '',
      playStore: 'https://play.google.com/store/apps/details?id=com.adbytee.pixi_walls',
      projectType: 'Android App',
      downloads: '50+',
      tags: ['Flutter', 'Dart', 'Android', 'iOS', 'Mobile', 'Wallpaper', 'HD', '4K', 'Pixi Walls'],
    ),
    ProjectModel(
      title: 'Number Calculator',
      appLogo: 'https://play-lh.googleusercontent.com/XCk4G2rFypKiEMebeYZ4bB1BVPlP44Z5wYUQ45yE61pBb1pbrS8Kc2cUukH_vW0z9Q=w240-h480-rw',
      description: "Number Calculator - EMI, GST, Percentage, Cuboid, Cube, Circular Cylinder, Circular Cone, Sphere, and Hemisphere.",
      website: '',
      gitHub: '',
      demo: 'https://youtube.com/shorts/Bv8sai46f94?feature=share',
      screenshot: Screenshots.numberCalculator,
      miStore: 'https://global.app.mi.com/details?lo=IN&la=en_US&id=com.adbytee.number_calculator',
      playStore: 'https://play.google.com/store/apps/details?id=com.adbytee.number_calculator',
      projectType: 'Android App',
      downloads: '100+',
      tags: ['Flutter', 'Dart', 'Android', 'iOS', 'Mobile', 'Calculator', 'Number Calculator'],
    ),
    ProjectModel(
      title: 'Mera Desh',
      appLogo: 'https://play-lh.googleusercontent.com/8lFI54oGg1vyy1fq3iBcXm0i0vjtI8tIbAqyO_tqNZ3BqmjUoeOtyH6EUsoDtVg19ZQ=w240-h480-rw',
      description:
          "Mera Desh - Made in INDIA 🇮🇳\n\nWe all do not know about INDIA or about our country that's why this app is made. This app for all the student who is preparing for any civil service (government job) exams, as well as civilians peoples and tourist to acquire more knowledge about INDIA and their history, culture and so on.",
      website: '',
      gitHub: '',
      demo: 'https://youtube.com/shorts/s82QAicfKQs?feature=share',
      screenshot: Screenshots.meraDesh,
      miStore: 'https://global.app.mi.com/details?lo=IN&la=en_US&id=com.adbytee.mera_desh',
      playStore: 'https://play.google.com/store/apps/details?id=com.adbytee.mera_desh',
      projectType: 'Android App',
      downloads: '500+',
      tags: ['Flutter', 'Dart', 'Android', 'iOS', 'Mobile', 'Mera Desh', 'India', 'Indian', 'History', 'Culture'],
    ),
    ProjectModel(
      title: 'Flat Banners',
      appLogo: 'https://cdn.icon-icons.com/icons2/2108/PNG/512/flutter_icon_130936.png',
      description: "A Flutter package for Offers, Promo and Invites banners. Supports Android and Web.",
      website: '',
      gitHub: 'https://github.com/om-chauhan/flat_banners',
      demo: '',
      screenshot: Screenshots.flatBanner,
      miStore: '',
      playStore: '',
      projectType: 'Flutter Package',
      downloads: '10+',
      tags: ['Flutter', 'Dart', 'Package', 'Banners', 'Promo Banners', 'Open Source'],
    ),
    ProjectModel(
      title: 'Image Slider Indicator',
      appLogo: 'https://cdn.icon-icons.com/icons2/2108/PNG/512/flutter_icon_130936.png',
      description: "Image Slider with indicator using flutter framework and dart language.",
      website: '',
      gitHub: 'https://github.com/om-chauhan/Image-Slider-Indicator-Flutter',
      demo: '',
      screenshot: Screenshots.imageSlider,
      miStore: '',
      playStore: '',
      projectType: 'Flutter Package',
      downloads: '10+',
      tags: ['Flutter', 'Dart', 'Carousal Slider', 'Open Source'],
    ),
    ProjectModel(
      title: 'Invoice Management Application UI',
      appLogo: 'https://cdn.icon-icons.com/icons2/2108/PNG/512/flutter_icon_130936.png',
      description: "Invoice Management Application Using Dart language and Flutter Framework Clean UI.",
      website: '',
      gitHub: 'https://github.com/om-chauhan/Invoice-Management-System-Flutter-UI',
      demo: 'https://youtube.com/shorts/2vNgmt6-dBo?feature=share',
      screenshot: Screenshots.invoiceUI,
      miStore: '',
      playStore: '',
      projectType: 'Flutter UI',
      tags: ['Flutter', 'Dart', 'Android', 'iOS', 'Mobile', 'Invoice', 'Management', 'UI', 'Clean UI', 'Open Source'],
    ),
    ProjectModel(
      title: 'E-Commerce App',
      appLogo: 'https://cdn.icon-icons.com/icons2/2108/PNG/512/flutter_icon_130936.png',
      description: "E-Commerce App - fetch data from Rest API.",
      website: '',
      gitHub: 'https://github.com/om-chauhan/Super-Store-Ecommerce-App-using-REST-Api-in-Flutter',
      demo: 'https://youtube.com/shorts/anrM-biWlzo?feature=share',
      screenshot: Screenshots.superStore,
      miStore: '',
      playStore: '',
      projectType: 'Flutter UI',
      tags: ['Flutter', 'Dart', 'Android', 'iOS', 'Mobile', 'E-Commerce', 'Super Store', 'REST API', 'Open Source'],
    ),
    ProjectModel(
      title: 'Simple Calculator',
      appLogo: 'https://cdn.icon-icons.com/icons2/2108/PNG/512/flutter_icon_130936.png',
      description: "A simple Calculator Applications by using Dart Language and Flutter Framework. which is support both Ios and Android.",
      website: '',
      gitHub: 'https://github.com/om-chauhan/Simple-Calculator-Flutter',
      demo: '',
      screenshot: Screenshots.simpleCalculator,
      miStore: '',
      playStore: '',
      projectType: 'Flutter App',
      tags: ['Flutter', 'Dart', 'Android', 'iOS', 'Mobile', 'Calculator', 'Open Source'],
    ),
    ProjectModel(
      title: 'Flutter Codebase',
      appLogo: 'https://codes.om-chauhan.co.in/icons/Icon-512.png',
      description:
          "Flutter Codebase is a Web App which is help to store all the useful website, Tutorials and Example of Code to achieve better code.",
      website: 'https://codes.om-chauhan.co.in/',
      gitHub: '',
      demo: '',
      screenshot: [],
      miStore: '',
      playStore: '',
      projectType: 'Web App',
      tags: ['Flutter', 'Dart', 'Codebase', 'Website Saved'],
    ),
    ProjectModel(
      title: 'Flutter Snippets',
      appLogo: 'https://cdn.icon-icons.com/icons2/2108/PNG/512/flutter_icon_130936.png',
      description: "Flutter Snippets is a collection of mostly used Widgets and Classes for Flutter developers.",
      website: 'https://marketplace.visualstudio.com/items?itemName=om-chauhan.flutter-snippets',
      gitHub: 'https://github.com/om-chauhan/flutter-snippets',
      demo: 'https://raw.githubusercontent.com/om-chauhan/flutter-snippets/fd303d1c7c0b5cf8ab69b6a7e21a4fd8bd96bcc7/flutter-snippets-demo.gif',
      screenshot: [],
      miStore: '',
      playStore: '',
      projectType: 'VS Code Extension',
      downloads: '2.6k+',
      tags: ['Flutter', 'Dart', 'Extension', 'VS Code', 'Snippets', 'Flutter Snippets'],
    ),
    ProjectModel(
      title: 'Create flutter package',
      appLogo: 'https://cdn.icon-icons.com/icons2/2108/PNG/512/flutter_icon_130936.png',
      description: "Create Flutter Package and Publish to the Pub.dev Beginner Friendly Steps",
      website: '',
      gitHub: 'https://gist.github.com/om-chauhan/4605653e6f2e41b8a0a46d6ab8e33b30',
      demo: '',
      screenshot: [],
      miStore: '',
      playStore: '',
      projectType: 'Gist',
      tags: ['Flutter', 'Dart', 'How to create package', 'Flutter Package', 'Pub.dev'],
    ),
  ];
}
