import 'package:om_chauhan/all_imports.dart';

class ProjectController {
  final projectList = [
    ProjectModel(
      title: 'Number Calculator',
      description:
          "Number Calculator - EMI, GST, Percentage, Cuboid, Cube, Circular Cylinder, Circular Cone, Sphere, and Hemisphere.",
      website: '',
      gitHub: '',
      top: true,
      demo: 'https://youtube.com/shorts/Bv8sai46f94?feature=share',
      screenshot: Screenshots.numberCalculator,
      miStore: 'https://global.app.mi.com/details?lo=IN&la=en_US&id=com.adbytee.number_calculator',
      playStore: 'https://play.google.com/store/apps/details?id=com.adbytee.number_calculator',
    ),
    ProjectModel(
      title: 'Mera Desh',
      description:
          "Mera Desh - Made in INDIA 🇮🇳\n\nWe all do not know about INDIA or about our country that's why this app is made. This app for all the student who is preparing for any civil service (government job) exams, as well as civilians peoples and tourist to acquire more knowledge about INDIA and their history, culture and so on.",
      website: '',
      gitHub: '',
      top: true,
      demo: 'https://youtube.com/shorts/s82QAicfKQs?feature=share',
      screenshot: Screenshots.meraDesh,
      miStore: 'https://global.app.mi.com/details?lo=IN&la=en_US&id=com.adbytee.mera_desh',
      playStore: 'https://play.google.com/store/apps/details?id=com.adbytee.mera_desh',
    ),
    ProjectModel(
      title: 'Flutter Codebase',
      description:
          "Flutter Codebase is a Web App which is help to store all the useful website, Tutorials and Example of Code to achieve better code.",
      website: 'https://codes.om-chauhan.co.in/',
      gitHub: '',
      top: false,
      demo: '',
      screenshot: [],
      miStore: '',
      playStore: '',
    ),
    ProjectModel(
      title: 'Flutter Snippets',
      description: "Flutter Snippets is a collection of mostly used Widgets and Classes for Flutter developers.",
      website: 'https://marketplace.visualstudio.com/items?itemName=om-chauhan.flutter-snippets',
      gitHub: 'https://github.com/om-chauhan/flutter-snippets',
      top: true,
      demo:
          'https://raw.githubusercontent.com/om-chauhan/flutter-snippets/fd303d1c7c0b5cf8ab69b6a7e21a4fd8bd96bcc7/flutter-snippets-demo.gif',
      screenshot: [],
      miStore: '',
      playStore: '',
    ),
    ProjectModel(
      title: 'Create flutter package',
      description: "Create Flutter Package and Publish to the Pub.dev Beginner Friendly Steps",
      website: '',
      gitHub: 'https://gist.github.com/om-chauhan/4605653e6f2e41b8a0a46d6ab8e33b30',
      top: true,
      demo: '',
      screenshot: [],
      miStore: '',
      playStore: '',
    ),
    ProjectModel(
      title: 'Flat Banners',
      description: "A Flutter package for Offers, Promo and Invites banners. Supports Android and Web.",
      website: 'https://pub.dev/packages/flat_banners',
      gitHub: 'https://github.com/om-chauhan/flat_banners',
      top: true,
      demo: '',
      screenshot: [],
      miStore: '',
      playStore: '',
    ),
    ProjectModel(
      title: 'Image Slider Indicator',
      description: "Image Slider with indicator using flutter framework and dart language.",
      website: 'https://pub.dev/packages/flat_banners',
      gitHub: 'https://github.com/om-chauhan/Image-Slider-Indicator-Flutter',
      top: false,
      demo: '',
      screenshot: [],
      miStore: '',
      playStore: '',
    ),
    ProjectModel(
      title: 'Invoice Management Application UI',
      description: "Invoice Management Application Using Dart language and Flutter Framework Clean UI.",
      website: '',
      gitHub: 'https://github.com/om-chauhan/Invoice-Management-System-Flutter-UI',
      top: false,
      demo: 'https://youtube.com/shorts/2vNgmt6-dBo?feature=share',
      screenshot: Screenshots.invoiceUI,
      miStore: '',
      playStore: '',
    ),
    ProjectModel(
      title: 'E-Commerce App',
      description: "E-Commerce App - fetch data from Rest API.",
      website: '',
      gitHub: 'https://github.com/om-chauhan/Super-Store-Ecommerce-App-using-REST-Api-in-Flutter',
      top: false,
      demo: 'https://youtube.com/shorts/anrM-biWlzo?feature=share',
      screenshot: Screenshots.superStore,
      miStore: '',
      playStore: '',
    ),
    ProjectModel(
      title: 'Simple Calculator',
      description:
          "A simple Calculator Applications by using Dart Language and Flutter Framework. which is support both Ios and Android.",
      website: '',
      gitHub: 'https://github.com/om-chauhan/Simple-Calculator-Flutter',
      top: false,
      demo: '',
      screenshot: Screenshots.simpleCalculator,
      miStore: '',
      playStore: '',
    ),
  ];
}
